import { Resend } from 'resend';

// Vercel will automatically inject RESEND_API_KEY from your project settings
const resend = new Resend(process.env.RESEND_API_KEY);

export default async function handler(req: any, res: any) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { userEmail, userName, pdfBase64, fileName } = req.body;

  if (!userEmail || !pdfBase64) {
    return res.status(400).json({ error: 'Missing required data' });
  }

  try {
    const data = await resend.emails.send({
      from: 'Homez Analysis <reports@homezbuyers.com.au>',
      to: [userEmail],
      cc: ['admin@homezbuyers.com.au'], // Sends a copy to your Microsoft account
      subject: `Investment Strategy Analysis: ${userName}`,
      html: `
        <!DOCTYPE html>
        <html>
        <body style="margin: 0; padding: 0; background-color: #FFFCED; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #e5e7eb; border-radius: 16px; overflow: hidden; margin-top: 40px; margin-bottom: 40px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
            <!-- Header -->
            <div style="background-color: #064E2C; padding: 32px; text-align: center;">
              <h1 style="color: #ffffff; margin: 0; font-family: 'Georgia', serif; letter-spacing: -0.5px; font-size: 24px;">HOMEZ</h1>
              <p style="color: #C6A672; margin: 5px 0 0 0; font-size: 10px; text-transform: uppercase; letter-spacing: 3px; font-weight: bold;">Buyers Advocacy</p>
            </div>
            
            <!-- Content -->
            <div style="padding: 40px 32px;">
              <h2 style="color: #064E2C; margin-top: 0; font-family: 'Georgia', serif;">Strategy Report Ready</h2>
              <p style="color: #555555; line-height: 1.6; font-size: 16px;">Hi ${userName},</p>
              <p style="color: #555555; line-height: 1.6; font-size: 16px;">Thank you for using the <strong>Homez Wealth Projection Engine (HWPE)</strong>.</p>
              <p style="color: #555555; line-height: 1.6; font-size: 16px;">Your comprehensive property investment analysis has been generated and is attached to this email. This report includes:</p>
              <ul style="color: #555555; line-height: 1.6; font-size: 15px; padding-left: 20px;">
                <li style="margin-bottom: 8px;">30-Year Wealth Velocity Projections</li>
                <li style="margin-bottom: 8px;">Detailed Cashflow & Tax Analysis</li>
                <li style="margin-bottom: 8px;">Capital Growth Forecasts</li>
              </ul>
              <div style="margin-top: 30px; padding: 20px; background-color: #f9fafb; border-radius: 8px; border-left: 4px solid #C6A672;">
                <p style="margin: 0; font-size: 14px; color: #666;"><strong>Next Steps:</strong> If you would like to discuss this strategy with a Senior Buyer's Advocate, please reply to this email.</p>
              </div>
            </div>

            <!-- Footer -->
            <div style="background-color: #f3f4f6; padding: 24px 32px; text-align: center; border-top: 1px solid #e5e7eb;">
              <p style="font-size: 12px; color: #9ca3af; margin: 0;">© ${new Date().getFullYear()} Homez Buyers Advocacy. All rights reserved.</p>
              <p style="font-size: 11px; color: #d1d5db; margin: 8px 0 0 0;">Generated by HWPE Engine v2.8</p>
            </div>
          </div>
        </body>
        </html>
      `,
      attachments: [
        {
          filename: fileName,
          content: pdfBase64,
        },
      ],
    });

    return res.status(200).json({ success: true, id: data.data?.id });
  } catch (error: any) {
    console.error("Resend Error:", error);
    return res.status(500).json({ error: error.message });
  }
}