
import { Resend } from 'resend';

// Vercel will automatically inject RESEND_API_KEY from your project settings
const resend = new Resend(process.env.RESEND_API_KEY);

export default async function handler(req: any, res: any) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { userEmail, userName, pdfBase64, fileName } = req.body;

  if (!userEmail || !pdfBase64) {
    return res.status(400).json({ error: 'Missing required data' });
  }

  try {
    const data = await resend.emails.send({
      from: 'Homez Analysis <reports@homezbuyers.com.au>',
      to: [userEmail],
      cc: ['admin@homezbuyers.com.au'], // Sends a copy to your Microsoft account
      subject: `Investment Analysis Report: ${userName}`,
      html: `
        <div style="font-family: sans-serif; color: #333;">
          <h2 style="color: #064E2C;">Property Strategy Report Prepared</h2>
          <p>Hi ${userName},</p>
          <p>Thank you for using the Homez Property Calculator. Please find your detailed property investment analysis attached as a PDF.</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 12px; color: #999;">This report was generated by Homez Buyers Advocacy.</p>
        </div>
      `,
      attachments: [
        {
          filename: fileName,
          content: pdfBase64,
        },
      ],
    });

    return res.status(200).json({ success: true, id: data.data?.id });
  } catch (error: any) {
    console.error("Resend Error:", error);
    return res.status(500).json({ error: error.message });
  }
}
